pipeline:
  build:
    image: node:latest
    commands: npm install
  publish:
    image: plugins/docker
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    email: mezentsev.valentin@gmail.com
    repo: tamriel/pet-assistant
    tag: latest
    file: Dockerfile
    when:
      branch: [ master ]
      evemt: [ push ]
