pipeline:
  build:
    image: node:latest
    commands: npm install
  test:
    image: node:latest
    commands: npm run test
  publish:
    image: plugins/docker:17.12
    username: tamriel
    password: tram061419
    repo: tamriel/pet-assistant
    tag: latest
    when:
      branch: [ master ]
      event: [ push ]
