kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    repo: tamriel/pet-assistant
    tag: latest
  when:
    branch:
      - master
    event:
      - push
