pipeline:
  # build:
  #   image: node:latest
  #   commands: npm install
  # test:
  #   image: node:latest
  #   commands: npm run test
  # publish:
  #   image: plugins/docker:17.12
  #   repo: tamriel/pet-assistant
  #   secrets: [ docker_username, docker_password ]
  #   tag: latest
  #   when:
  #     branch: [ master ]
  #     event: [ push ]
  deploy:
    pull: true
    image: appleboy/drone-ssh
    port: 22
    secrets:
        - source: DRONE_RSA
          target: ssh_key
        - source: HOST_NAME
          target: ssh_host
        - source: SSH_USER_NAME
          target: ssh_username
    script:
      - echo ${ssh_key}
      - echo ${ssh_username}
