pipeline:
  publish:
    image: plugins/docker:17.12
    repo: tamriel/pet-assistant
    secrets: [ docker_username, docker_password ]
    tag: latest
    when:
      branch: [ master ]
      event: [ push ]
