version: "3"
services:
  app:
    image: homeless-pet-assistant
    volumes:
      - .:/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3000:8080
    command: npm run dev
