version: "3"
services:
  app:
    build: .
    volumes:
      - .:/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: pm2-runtime start ecosystem.config.js --watch
